import { Link } from 'react-router-dom';
import './Footer.css';

// Inline SVG icons for LinkedIn, X (Twitter), and Instagram
function LinkedInIcon() {
  return (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"/>
      <rect x="2" y="9" width="4" height="12"/><circle cx="4" cy="4" r="2"/>
    </svg>
  );
}

function XIcon() {
  return (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
      <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"/>
    </svg>
  );
}

function InstagramIcon() {
  return (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <rect x="2" y="2" width="20" height="20" rx="5" ry="5"/>
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"/>
      <line x1="17.5" y1="6.5" x2="17.51" y2="6.5"/>
    </svg>
  );
}

export default function Footer() {
  const scrollToSection = (id) => {
    document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' });
  };

  return (
    <footer className="footer" id="support">
      <div className="container">
        <div className="footer-grid">
          {/* Brand */}
          <div className="footer-brand">
            <div className="footer-logo">
              <div className="footer-logo-icon">H</div>
              HireMe<span>.co</span>
            </div>
            <p>
              India's verified skill-matching platform. Connecting talented students 
              from every college with top companies — powered by AI, driven by fairness.
            </p>
            <div className="footer-socials">
              <a href="https://linkedin.com" target="_blank" rel="noopener noreferrer" className="footer-social-link" aria-label="LinkedIn">
                <LinkedInIcon />
              </a>
              <a href="https://x.com" target="_blank" rel="noopener noreferrer" className="footer-social-link" aria-label="X (Twitter)">
                <XIcon />
              </a>
              <a href="https://instagram.com" target="_blank" rel="noopener noreferrer" className="footer-social-link" aria-label="Instagram">
                <InstagramIcon />
              </a>
            </div>
          </div>

          {/* Platform */}
          <div className="footer-column">
            <h4>Platform</h4>
            <ul>
              <li><button onClick={() => scrollToSection('features')} className="navbar-link" style={{ color: 'var(--slate-400)', fontSize: '0.875rem', background: 'none', border: 'none', cursor: 'pointer', padding: 0 }}>Features</button></li>
              <li><button onClick={() => scrollToSection('for-students')} style={{ color: 'var(--slate-400)', fontSize: '0.875rem', background: 'none', border: 'none', cursor: 'pointer', padding: 0 }}>For Students</button></li>
              <li><button onClick={() => scrollToSection('for-companies')} style={{ color: 'var(--slate-400)', fontSize: '0.875rem', background: 'none', border: 'none', cursor: 'pointer', padding: 0 }}>For Companies</button></li>
              <li><Link to="/auth">Get Started</Link></li>
            </ul>
          </div>

          {/* Resources */}
          <div className="footer-column">
            <h4>Resources</h4>
            <ul>
              <li><a href="#support">Support</a></li>
              <li><a href="#terms">Terms & Conditions</a></li>
              <li><a href="#privacy">Privacy Policy</a></li>
              <li><a href="mailto:support@hiremeco.ai">Contact Us</a></li>
            </ul>
          </div>

          {/* Support */}
          <div className="footer-support">
            <h4>Contact & Support</h4>
            <p>
              Need help? Reach our 24/7 support desk at{' '}
              <a href="mailto:support@hiremeco.ai">support@hiremeco.ai</a>{' '}
              or chat with our bot. We are committed to a safe, spam-free internship 
              ecosystem for India's youth.
            </p>
          </div>
        </div>

        <hr className="footer-divider" />

        <div className="footer-bottom" id="terms">
          <div className="footer-terms">
            <strong>Terms & Conditions Applied:</strong> By using HireMe.co, you agree to our verified matching protocol. 
            Companies must provide a minimum stipend for all "Verified" listings. All Skill-Scores are generated by our 
            proprietary AI and are for matching purposes only. User data is encrypted and protected under Indian Data Privacy Laws.
          </div>
          <div className="footer-copyright">
            <span>© 2026 HireMe.co — All rights reserved.</span>
            <span>Made with ❤️ for Bharat's talent</span>
          </div>
        </div>
      </div>
    </footer>
  );
}
